#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: wordpress-cm
#date:

---
apiVersion: v1
kind: Pod
metadata:
  name: wordpress-pod
spec:
  containers:
    - name: wordpress
      image: wordpress:latest 
      ports: 
        - containerPort: 80

