FROM mysql:latest
ENV MYSQL_ROOT_PASSWORD=root_password
ENV MYSQL_DATABASE=hioxtraining_wp109
ENV MYSQL_USER=hioxtraining_wp109
ENV MYSQL_PASSWORD=r0EOt(3-3!S-bpU)
COPY init.sql /docker-entrypoint-initdb.d/

