prometheus:
  image:
    repository: prom/prometheus
    tag: latest
  service:
    type: LoadBalancer
    port: 9090
  config:
    prometheus.yml: |
      global:
        scrape_interval: 15s
      scrape_configs:
        - job_name: 'prometheus'
          static_configs:
            - targets: ['localhost:9090']
        - job_name: 'node-exporter'
          static_configs:
            - targets: ['node-exporter:9100']

grafana:
  image:
    repository: grafana/grafana
    tag: latest
  service:
    type: LoadBalancer
    port: 3000

nodeExporter:
  image:
    repository: prom/node-exporter
    tag: latest
  service:
    type: ClusterIP
    port: 9100

