version: '3.8'

services:
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - wordpress

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: hioxtraining_wp109
      MYSQL_USER: hioxtraining_wp109
      MYSQL_PASSWORD: r0EOt(3-3!S-bpU)
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  wordpress:
    image: wordpress:latest
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: hioxtraining_wp109
      WORDPRESS_DB_PASSWORD: r0EOt(3-3!S-bpU)
      WORDPRESS_DB_NAME: hioxtraining_wp109
    ports:
      - "8080:80"
    volumes:
      - ./additional/DB_file.sql:/docker-entrypoint-initdb.d/DB_file.sql
    depends_on:
      - mysql

volumes:
  mysql_data:

