apiVersion: v1
kind: Service
metadata:
  name: node-exporter
spec:
  type: {{ .Values.nodeExporter.service.type }}
  selector:
    app: node-exporter
  ports:
    - port: {{ .Values.nodeExporter.service.port }}
      targetPort: 9100

